[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
# Serve JavaScript files with the correct MIME type
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"